/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class addDoctor extends javax.swing.JFrame {
    
    Boolean result;
    Connection con1;
    PreparedStatement insert,update,delete;

    /**
     * Creates new form addDoctor
     */
    public addDoctor() {
        initComponents();
        doctorId.setEditable(false);
//        setimg();
//        jPanel1.setBackground(new Color(255,255,255,120));
    }
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };

    private void table_update()
    {
        int c;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            insert = con1.prepareStatement("select * from doctor");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) docAddTable.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2 = new Vector ();
                for (int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("docId"));
                    v2.add(rs.getString("docName"));
                    v2.add(rs.getString("specialization"));
                    v2.add(rs.getString("phonNo"));
                    v2.add(rs.getString("email"));
                    v2.add(rs.getString("docFee"));
                    v2.add(rs.getString("docAvailability"));
                    v2.add(rs.getString("docCount"));
                    v2.add(rs.getString("weekdayTime"));
                    v2.add(rs.getString("weekendTime"));
                    v2.add(rs.getString("weekday"));
                    v2.add(rs.getString("weekend"));
                }
                
                df.addRow(v2);
            }
        }

        catch (SQLException ex) {
           Logger.getLogger(docReport.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex) {
           Logger.getLogger(docReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addDocLable = new javax.swing.JLabel();
        docNameLable = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        docSpecLable = new javax.swing.JLabel();
        txtDoctorSpecility = new javax.swing.JComboBox<>();
        docFee = new javax.swing.JLabel();
        docFeeFeild = new javax.swing.JTextField();
        docEmailLable = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        docPhnLable = new javax.swing.JLabel();
        docPhnTextField = new javax.swing.JTextField();
        docChaDayLable = new javax.swing.JLabel();
        docChnlTimeLable = new javax.swing.JLabel();
        docWeekdayLable = new javax.swing.JLabel();
        WeekdayTimeDropDown = new javax.swing.JComboBox<>();
        weekEndLable = new javax.swing.JLabel();
        weekendTimeDropdown = new javax.swing.JComboBox<>();
        docAddBtn = new javax.swing.JButton();
        docClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        docAddTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        docIdLable = new javax.swing.JLabel();
        doctorId = new javax.swing.JTextField();
        doctorCountLable = new javax.swing.JLabel();
        doctorCount = new javax.swing.JTextField();
        weekdayChannel = new javax.swing.JLabel();
        weekendChannel = new javax.swing.JLabel();
        weekdayChannelDropDown = new javax.swing.JComboBox<>();
        weekendChannelDropDown = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        backg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addDocLable.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addDocLable.setText("ADD NEW DOCTOR");

        docNameLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docNameLable.setText("Doctor Name:");

        txtDoctorName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        docSpecLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docSpecLable.setText("Doctor Specility:");

        txtDoctorSpecility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neurologist", "Cardiologist", "Physician", "Psychiatrist", "Radiology", "Urology", "Dermatology", " " }));
        txtDoctorSpecility.setBorder(null);

        docFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docFee.setText("Doctor fee:");

        docFeeFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        docFeeFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docFeeFeildActionPerformed(evt);
            }
        });

        docEmailLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docEmailLable.setText("Email:");

        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        docPhnLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docPhnLable.setText("Phone No:");

        docPhnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        docPhnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docPhnTextFieldActionPerformed(evt);
            }
        });

        docChaDayLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docChaDayLable.setText("Channelling Day: ");

        docChnlTimeLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docChnlTimeLable.setText("Chanelling Time:");

        docWeekdayLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docWeekdayLable.setText("Weekday");

        WeekdayTimeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "8.00-10.00 a.m", "1.00-3.00 p.m", "4.00-6.00 p.m", "6.00-8.00 p.m" }));
        WeekdayTimeDropDown.setBorder(null);
        WeekdayTimeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeekdayTimeDropDownActionPerformed(evt);
            }
        });

        weekEndLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weekEndLable.setText("Weekend");

        weekendTimeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "6.00-8.00 a.m", "10.00-12.00 a.m", "2.00-4.00 p.m", "8.00-10.00 p.m" }));
        weekendTimeDropdown.setBorder(null);

        docAddBtn.setBackground(new java.awt.Color(53, 92, 125));
        docAddBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        docAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        docAddBtn.setText("Add");
        docAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docAddBtnActionPerformed(evt);
            }
        });

        docClearBtn.setBackground(new java.awt.Color(53, 92, 125));
        docClearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        docClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        docClearBtn.setText("Clear");
        docClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docClearBtnActionPerformed(evt);
            }
        });

        docAddTable.setBackground(new java.awt.Color(153, 153, 255));
        docAddTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        docAddTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docAddTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Dr.name", "Speciality", "Phone no", "Email", "Doc Fee", "Availability", "No of patients", "WeekdayTime", "WeekendTime", "Weekday", "Weekend"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        docAddTable.setGridColor(new java.awt.Color(153, 153, 255));
        docAddTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docAddTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docAddTable);

        backBtn.setBackground(new java.awt.Color(53, 92, 125));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        docIdLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docIdLable.setText("Doctor Id:");

        doctorId.setBackground(new java.awt.Color(214, 234, 245));
        doctorId.setBorder(null);
        doctorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorIdActionPerformed(evt);
            }
        });

        doctorCountLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doctorCountLable.setText("No of patients");

        doctorCount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        doctorCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorCountActionPerformed(evt);
            }
        });

        weekdayChannel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weekdayChannel.setText("Weekday");

        weekendChannel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weekendChannel.setText("Weekend");

        weekdayChannelDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        weekdayChannelDropDown.setBorder(null);

        weekendChannelDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Saturday", "Sunday" }));
        weekendChannelDropDown.setBorder(null);
        weekendChannelDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekendChannelDropDownActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(53, 92, 125));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(53, 92, 125));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(addDocLable, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(docChnlTimeLable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(docWeekdayLable))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(weekEndLable)))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(WeekdayTimeDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weekendTimeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(docEmailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(docPhnLable))
                                        .addGap(52, 63, Short.MAX_VALUE))
                                    .addComponent(doctorCountLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(docFee, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(docNameLable)
                                        .addComponent(docIdLable)
                                        .addComponent(docSpecLable))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(docPhnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(doctorCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDoctorName)
                                        .addComponent(txtDoctorSpecility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(docFeeFeild)
                                        .addComponent(doctorId, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(docChaDayLable)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weekdayChannel)
                            .addComponent(weekendChannel))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weekendChannelDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weekdayChannelDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(docClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(addDocLable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(docIdLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doctorId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDoctorSpecility, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docSpecLable))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docFeeFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docFee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docEmailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docPhnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docPhnLable))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorCount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorCountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docChaDayLable)
                            .addComponent(weekdayChannel)
                            .addComponent(weekdayChannelDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weekendChannel)
                            .addComponent(weekendChannelDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(docWeekdayLable)
                                .addComponent(docChnlTimeLable))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(WeekdayTimeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(weekEndLable)
                                    .addComponent(weekendTimeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, 1509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorCountActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        adminDoctorMain back1 = new adminDoctorMain();
        back1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void docAddTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docAddTableMouseClicked

        DefaultTableModel df = (DefaultTableModel) docAddTable.getModel();
        int selectedIndex = docAddTable.getSelectedRow();
        
        doctorId.setText(df.getValueAt(selectedIndex, 0).toString());
        txtDoctorName.setText(df.getValueAt(selectedIndex, 1).toString());
        txtDoctorSpecility.setSelectedItem(df.getValueAt(selectedIndex, 2).toString());
        docFeeFeild.setText(df.getValueAt(selectedIndex, 3).toString());
        txtEmail.setText(df.getValueAt(selectedIndex, 4).toString());
        docPhnTextField.setText(df.getValueAt(selectedIndex, 5).toString());
        WeekdayTimeDropDown.setSelectedItem(df.getValueAt(selectedIndex, 6).toString());
        weekendTimeDropdown.setSelectedItem(df.getValueAt(selectedIndex, 7).toString());
        doctorCount.setText(df.getValueAt(selectedIndex, 8).toString());
        weekdayChannelDropDown.setSelectedItem(df.getValueAt(selectedIndex, 9).toString());
        weekendChannelDropDown.setSelectedItem(df.getValueAt(selectedIndex, 10).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_docAddTableMouseClicked

    private void docClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docClearBtnActionPerformed
        doctorId.setText("");
        txtDoctorName.setText("");
        txtEmail.setText("");
        docFeeFeild.setText("");
        txtDoctorSpecility.setSelectedItem("None");
        docPhnTextField.setText("");
        WeekdayTimeDropDown.setSelectedItem("None");
        weekendTimeDropdown.setSelectedItem("None");
        doctorCount.setText("");
        weekdayChannelDropDown.setSelectedItem("None");
        weekendChannelDropDown.setSelectedItem("None");
    }//GEN-LAST:event_docClearBtnActionPerformed

    private void docAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docAddBtnActionPerformed
        String dname=txtDoctorName.getText();
        String demail =txtEmail.getText();
        String docFee1 = docFeeFeild.getText();
        String dspecialty =txtDoctorSpecility.getSelectedItem().toString();
        String phnNo =docPhnTextField.getText();
        String weekdayTime= WeekdayTimeDropDown.getSelectedItem().toString();
        String weekendTime= weekendTimeDropdown.getSelectedItem().toString();
        String doctorCount1= doctorCount.getText();
        String weekdayChannel1= weekdayChannelDropDown.getSelectedItem().toString();
        String weekendChannel1= weekendChannelDropDown.getSelectedItem().toString();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");
            
            if(dname.equals("") || demail.equals("") || phnNo.equals("") ||doctorCount1.equals("") ){
                JOptionPane.showMessageDialog(this,"Please enter doctor details!");
            }
            else{
                String PATTERN = "^[a-zA-Z]{0,30}$";
                Pattern patt = Pattern.compile(PATTERN);
                Matcher match;
                match = patt.matcher(txtDoctorName.getText());
                if(!match.matches()){
                    JOptionPane.showMessageDialog(this,"Please enter name!");
                }
                else{
                    String PATTERN1 = "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]{0,5}$";
                    Pattern patt1 = Pattern.compile(PATTERN1);
                    Matcher match1;
                    match1 = patt1.matcher(docPhnTextField.getText());

                    if(!match1.matches()){
                        JOptionPane.showMessageDialog(this,"Please enter a valid phone number!");
                    }
                    

                    else{
                        String PATTERN2 = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
                                         //^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$
                        Pattern patt2 = Pattern.compile(PATTERN2);
                        Matcher match2;
                        match2 = patt2.matcher(txtEmail.getText());
                        if(!match2.matches()){
                            JOptionPane.showMessageDialog(this,"Enter a valid Email");
                        }
                        else{
                            insert = con1.prepareStatement("Select 1 from doctor where email = ?");
                            insert.setString(1, txtEmail.getText());

                            ResultSet r = insert.executeQuery();

                            int a = 0;

                            while(r.next()){
                                a = r.getInt("1");
                            }
                            if(a == 1){
                                JOptionPane.showMessageDialog(this,"E-mail already exists!");
                            }
                            else{
                                insert = con1.prepareStatement("Select 1 from doctor where docName = ?");
                                insert.setString(1, txtDoctorName.getText());

                                ResultSet r1 = insert.executeQuery();

                                int a1 = 0;

                                while(r1.next()){
                                    a1 = r1.getInt("1");
                                }
                                if(a1 == 1){
                                    JOptionPane.showMessageDialog(this,"Doctor name  already exists!");
                                }
                                else{
                                    insert = con1.prepareStatement("insert into doctor(docName,specialization,email,phonNo,docCount,docFee,weekdayTime,weekendTime,weekday,weekend) values(?,?,?,?,?,?,?,?,?,?)");

                                    insert.setString(1,dname);
                                    insert.setString(2,dspecialty );
                                    insert.setString(3,demail );
                                    insert.setString(4,phnNo );
                                    insert.setString(5,doctorCount1 );
                                    insert.setString(6,docFee1 );
                                    insert.setString(7,weekdayTime);
                                    insert.setString(8,weekendTime);
                                    insert.setString(9,weekdayChannel1);
                                    insert.setString(10,weekendChannel1);
                                    insert.executeUpdate();
                                    
                                    JOptionPane.showMessageDialog(this,"Doctor Added");
                                    table_update();
                             
                                }
                            }
                        }
                    }
                }
            }
        }
        catch (ClassNotFoundException ex) {
            //JOptionPane.showMessageDialog(this, "Cant insert ");
            Logger.getLogger(addDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(addDoctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_docAddBtnActionPerformed

    private void WeekdayTimeDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeekdayTimeDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeekdayTimeDropDownActionPerformed

    private void docPhnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docPhnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docPhnTextFieldActionPerformed

    private void docFeeFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docFeeFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docFeeFeildActionPerformed

    private void doctorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorIdActionPerformed

    private void weekendChannelDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekendChannelDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekendChannelDropDownActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        adminLogin adLog = new adminLogin();
        adLog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtDoctorName.setText("Sunil");
        txtEmail.setText("sunil@gmail.com");
        docFeeFeild.setText("1200");
        docPhnTextField.setText("0715648963");
        doctorCount.setText("15");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new addDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> WeekdayTimeDropDown;
    private javax.swing.JLabel addDocLable;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backg;
    private javax.swing.JButton docAddBtn;
    private javax.swing.JTable docAddTable;
    private javax.swing.JLabel docChaDayLable;
    private javax.swing.JLabel docChnlTimeLable;
    private javax.swing.JButton docClearBtn;
    private javax.swing.JLabel docEmailLable;
    private javax.swing.JLabel docFee;
    private javax.swing.JTextField docFeeFeild;
    private javax.swing.JLabel docIdLable;
    private javax.swing.JLabel docNameLable;
    private javax.swing.JLabel docPhnLable;
    private javax.swing.JTextField docPhnTextField;
    private javax.swing.JLabel docSpecLable;
    private javax.swing.JLabel docWeekdayLable;
    private javax.swing.JTextField doctorCount;
    private javax.swing.JLabel doctorCountLable;
    private javax.swing.JTextField doctorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JComboBox<String> txtDoctorSpecility;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel weekEndLable;
    private javax.swing.JLabel weekdayChannel;
    private javax.swing.JComboBox<String> weekdayChannelDropDown;
    private javax.swing.JLabel weekendChannel;
    private javax.swing.JComboBox<String> weekendChannelDropDown;
    private javax.swing.JComboBox<String> weekendTimeDropdown;
    // End of variables declaration//GEN-END:variables
}
