/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anji
 */
public class AddLabTest extends javax.swing.JFrame {
    
        Boolean result;
        Connection con1;
        PreparedStatement insert, delete, update;


    /**
     * Creates new form addLabTest
     */
    public AddLabTest() {
        initComponents();
        //setimg();
        //jPanel1.setBackground(new Color(255,255,255,120));
    }
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };
    
        private void table_update()
    {
        int c;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");
            
            insert = con1.prepareStatement("select * from labtest");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) lab.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("testId"));
                    v2.add(rs.getString("testName"));
                    v2.add(rs.getString("category"));
                    v2.add(rs.getString("charge"));
                    v2.add(rs.getString("issuingTime"));
                    v2.add(rs.getString("description"));
                }
                
                df.addRow(v2);
            }
        }
            
        catch (ClassNotFoundException ex) {
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testIdLabel = new javax.swing.JLabel();
        testId = new javax.swing.JLabel();
        testNameLabel = new javax.swing.JLabel();
        testName = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryDropdown = new javax.swing.JComboBox<>();
        chargeLabel = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();
        reportIssueLabel = new javax.swing.JLabel();
        hrsDropdown = new javax.swing.JComboBox<>();
        hrsLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextArea = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        addLabTestLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lab = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        demoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        testIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testIdLabel.setText("Test Id");

        testId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        testNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testNameLabel.setText("Test Name");

        testName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testNameActionPerformed(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryLabel.setText("Category");

        categoryDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Category", "Test", "Scan" }));
        categoryDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDropdownActionPerformed(evt);
            }
        });

        chargeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chargeLabel.setText("Charge");

        charge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeActionPerformed(evt);
            }
        });

        reportIssueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportIssueLabel.setText("Report issues after");

        hrsDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hrsDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "8", "24", "48" }));
        hrsDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrsDropdownActionPerformed(evt);
            }
        });

        hrsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hrsLabel.setText("hrs");

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descriptionLabel.setText("Description");

        descTextArea.setColumns(20);
        descTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descTextArea.setRows(5);
        descriptionTextArea.setViewportView(descTextArea);

        addButton.setBackground(new java.awt.Color(53, 92, 125));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addLabTestLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addLabTestLabel.setText("Add Lab Test");

        lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Id", "Test Name", "Category", "Charge", "Report issues after", "Description"
            }
        ));
        lab.setRowHeight(25);
        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lab);

        jButton5.setBackground(new java.awt.Color(52, 92, 125));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Show");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(52, 92, 125));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(53, 92, 125));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(52, 92, 125));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        demoBtn.setBackground(new java.awt.Color(53, 92, 125));
        demoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        demoBtn.setForeground(new java.awt.Color(255, 255, 255));
        demoBtn.setText("Demo");
        demoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryLabel)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportIssueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addLabTestLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(testId, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(642, 642, 642)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(testName)
                                    .addComponent(categoryDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hrsDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hrsLabel))
                                    .addComponent(charge)
                                    .addComponent(descriptionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(demoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabTestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(testIdLabel)
                        .addGap(19, 19, 19)
                        .addComponent(testNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(categoryLabel)
                        .addGap(28, 28, 28)
                        .addComponent(chargeLabel)
                        .addGap(27, 27, 27)
                        .addComponent(reportIssueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(descriptionLabel)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(testName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(categoryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hrsDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hrsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(descriptionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testNameActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String  ltname = testName.getText();
        String lcategory = categoryDropdown.getSelectedItem().toString();
        String  lcharge = charge.getText();
        String  Hours = hrsDropdown.getSelectedItem().toString();
        String ldescription = descTextArea.getText();

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            if(ltname.equals("") || lcategory.equals("") || lcharge.equals("") || Hours.equals("") || ldescription.equals("")){
                JOptionPane.showMessageDialog(this,"Please enter Lab test details!");
            }
            else{
                String PATTERN = "\\s*[\\da-zA-Z][\\da-zA-Z\\s]*$";
                Pattern patt = Pattern.compile(PATTERN);
                Matcher match;
                match = patt.matcher(testName.getText());
                if(!match.matches()){
                    JOptionPane.showMessageDialog(this,"Please enter a Valid Test Name!");
                }
                else{
                    String PATTERN2 = "^[0-9]{0,9}$";
                    Pattern patt2 = Pattern.compile(PATTERN);
                    Matcher match2;
                    match2 = patt2.matcher(charge.getText());
                    if(!match.matches()){
                        JOptionPane.showMessageDialog(this,"Please enter letters!");
                    }
                    else{
                        String PATTERN1 = "^[0-9]{0,9}$";
                        Pattern patt1 = Pattern.compile(PATTERN1);
                        Matcher match1;
                        match1 = patt1.matcher(charge.getText());

                        if(!match1.matches()){
                            JOptionPane.showMessageDialog(this,"Please enter numbers!");
                        }

                        else{
                            insert = con1.prepareStatement("Select 1 from labtest where testName = ?");
                            insert.setString(1, testName.getText());

                            ResultSet r = insert.executeQuery();

                            int a = 0;

                            while(r.next()){
                                a = r.getInt("1");
                            }
                            if(a == 1){
                                JOptionPane.showMessageDialog(this,"Lab Test is already added!");
                            }
                            else{
                                insert = con1.prepareStatement("insert into labtest(testName,category,charge,issuingTime,description) values(?,?,?,?,?)");

                                insert.setString(1, testName.getText());
                                insert.setString(2, categoryDropdown.getSelectedItem().toString());
                                insert.setString(3, charge.getText());
                                insert.setString(4, hrsDropdown.getSelectedItem().toString());
                                insert.setString(5, descTextArea.getText());
                                insert.executeUpdate();

                                JOptionPane.showMessageDialog(this, "Lab Test Added");
                                table_update();
                            }
                        }
                    }
                }
            }

        }
        catch (ClassNotFoundException ex) {
            //JOptionPane.showMessageDialog(this, "Cant insert ");
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        labAssistantMain la = new labAssistantMain();
        la.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeActionPerformed

    private void categoryDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryDropdownActionPerformed

    private void labMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) lab.getModel();
        int selectedIndex = lab.getSelectedRow();

        testId.setText(df.getValueAt(selectedIndex, 0).toString());
        testName.setText(df.getValueAt(selectedIndex, 1).toString());
        categoryDropdown.setSelectedItem(df.getValueAt(selectedIndex, 2).toString());
        charge.setText(df.getValueAt(selectedIndex, 3).toString());
        hrsDropdown.setSelectedItem(df.getValueAt(selectedIndex, 4).toString());
        descTextArea.setText(df.getValueAt(selectedIndex, 5).toString());
    }//GEN-LAST:event_labMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int c;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            insert = con1.prepareStatement("select * from labtest");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) lab.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("testId"));
                    v2.add(rs.getString("testName"));
                    v2.add(rs.getString("category"));
                    v2.add(rs.getString("charge"));
                    v2.add(rs.getString("issuingTime"));
                    v2.add(rs.getString("description"));
                }

                df.addRow(v2);
            }
        }

        catch (ClassNotFoundException ex) {
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(AddLabTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void hrsDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrsDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrsDropdownActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //when click on clear button every fields should be null
        testId.setText(null);
        testName.setText(null);
        categoryDropdown.setSelectedItem(null);
        charge.setText(null);
        hrsDropdown.setSelectedItem(null);
        descTextArea.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //When logout from page,it redirects to the login page
        int response=JOptionPane.showConfirmDialog(this,"Do you really want to logout?","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            LabAssistantLogin lab = new LabAssistantLogin();
            lab.setVisible(true);
            this.dispose();
        }
        else {

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void demoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoBtnActionPerformed
        // TODO add your handling code here:
        testName.setText("Full Blood Count");
        charge.setText("2000");
        descTextArea.setText("Check the types and numbers of cells in your blood, including red blood cells, white blood cells and platelets");
    }//GEN-LAST:event_demoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLabTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLabTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLabTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLabTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLabTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabTestLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> categoryDropdown;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField charge;
    private javax.swing.JLabel chargeLabel;
    private javax.swing.JButton demoBtn;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionTextArea;
    private javax.swing.JComboBox<String> hrsDropdown;
    private javax.swing.JLabel hrsLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lab;
    private javax.swing.JLabel reportIssueLabel;
    private javax.swing.JLabel testId;
    private javax.swing.JLabel testIdLabel;
    private javax.swing.JTextField testName;
    private javax.swing.JLabel testNameLabel;
    // End of variables declaration//GEN-END:variables
}
