/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author acer
 */
public class MobileServiceAddPackage extends javax.swing.JFrame {
    Boolean result;
    Connection con1;
    PreparedStatement insert, delete, update;
    private PreparedStatement countStmt;    
    /**
     * Creates new form addServicePackage
     */
    public MobileServiceAddPackage() {
        initComponents();
//        setimg();
//        jPanel1.setBackground(new Color(255,255,255,120));
    }
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };

        private void table_update()
    {
        int c;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            insert = con1.prepareStatement("select * from servicepackage");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("packageId"));
                    v2.add(rs.getString("serviceName"));
                    v2.add(rs.getString("packageCount"));
                    v2.add(rs.getString("PackageFee"));
                    v2.add(rs.getString("serviceDescription"));
                }

                df.addRow(v2);
            }
        }

        catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicePackage = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        addServiceServiceName = new javax.swing.JLabel();
        addServiceCount = new javax.swing.JLabel();
        addServiceFee = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JTextField();
        serviceCountField = new javax.swing.JTextField();
        serviceFeeField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        serviceId = new javax.swing.JLabel();
        demoBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Service Package");

        jButton7.setBackground(new java.awt.Color(53, 92, 125));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(53, 92, 125));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Show");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        servicePackage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Mobile Service Name", "Count", "Service Fee", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        servicePackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicePackageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(servicePackage);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addServiceServiceName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceServiceName.setText("Mobile Service Name  ");

        addServiceCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceCount.setText("Count  ");

        addServiceFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceFee.setText("Service Fee  ");

        serviceNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serviceNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceNameFieldActionPerformed(evt);
            }
        });

        serviceCountField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serviceCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCountFieldActionPerformed(evt);
            }
        });

        serviceFeeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addButton.setBackground(new java.awt.Color(53, 92, 125));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(53, 92, 125));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(53, 92, 125));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Description");

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane4.setViewportView(descriptionArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Service Id");

        serviceId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        demoBtn.setBackground(new java.awt.Color(53, 92, 125));
        demoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        demoBtn.setForeground(new java.awt.Color(255, 255, 255));
        demoBtn.setText("DEMO");
        demoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addServiceServiceName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(serviceId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(serviceCountField)
                                        .addComponent(serviceFeeField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(demoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(deleteButton)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addServiceCount)
                            .addComponent(addServiceFee)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(serviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(addServiceServiceName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addServiceCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addServiceFee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(demoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jButton5.setBackground(new java.awt.Color(53, 92, 125));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceNameFieldActionPerformed

    private void serviceCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceCountFieldActionPerformed
/*
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
       
        
    }                                         

    private void servicePackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicePackageMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_servicePackageMouseClicked
*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MobileServiceMain back = new MobileServiceMain();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        int c;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            insert = con1.prepareStatement("select * from servicepackage"); 

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("packageId"));
                    v2.add(rs.getString("serviceName"));
                    v2.add(rs.getString("packageCount"));
                    v2.add(rs.getString("PackageFee"));
                    v2.add(rs.getString("serviceDescription"));
                }

                df.addRow(v2);
            }
        }


        catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
        int selectedIndex = servicePackage.getSelectedRow();

        String serviceName = serviceNameField.getText();
        String serviceCount = serviceCountField.getText();
        String serviceFee = serviceFeeField.getText();
        String description = descriptionArea.getText();


        if(serviceName.equals("") || serviceCount.equals("") || serviceFee.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter Service Package details!");
        }
        else{
            String PATTERN = "^\\s*[\\da-zA-Z][\\da-zA-Z\\s]*$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match;
            match = patt.matcher(serviceNameField.getText());
            if(!match.matches()){
                JOptionPane.showMessageDialog(this,"Please only enter letters!");
            }
            else{
                String PATTERN2 = "^[0-9]{0,9}$";
                Pattern patt2 = Pattern.compile(PATTERN);
                Matcher match2;
                match2 = patt2.matcher(serviceCountField.getText());
                if(!match.matches()){
                    JOptionPane.showMessageDialog(this,"Please enter numbers!");
                }
                else{
                    String PATTERN1 = "^[0-9]{0,9}$";
                    Pattern patt1 = Pattern.compile(PATTERN1);
                    Matcher match1;
                    match1 = patt1.matcher(serviceFeeField.getText());

                    if(!match1.matches()){
                        JOptionPane.showMessageDialog(this,"Please enter numbers!");
                    }

                    else{
                        try {
                            Class.forName("com.mysql.jdbc.Driver");

                            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

                            insert = con1.prepareStatement("update servicepackage set serviceName = ?, packageCount = ? , PackageFee = ?, serviceDescription = ? where packageId = ?");


                            insert.setString(1, serviceNameField.getText());
                            insert.setString(2, serviceCountField.getText());
                            insert.setString(3, serviceFeeField.getText());
                            insert.setString(4, descriptionArea.getText());
                            insert.setString(5, serviceId.getText());
                            insert.executeUpdate();

                            insert.executeUpdate();

                            JOptionPane.showMessageDialog(this, "Record Updated");
                            //table_update();

                            serviceId.setText("");
                            serviceNameField.setText("");
                            serviceCountField.setText("");
                            serviceFeeField.setText("");
                            descriptionArea.setText("");
                        }
                        catch (SQLException ex) {

                            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        catch (ClassNotFoundException ex){
                            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        table_update();
                    }
                }
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
                String Did = null;
        try {

            delete = con1.prepareStatement("DELETE FROM servicepackage where packageId = ?") ;

            delete.setString(1, serviceId.getText());
            delete.executeUpdate();


            DefaultTableModel tblModel = (DefaultTableModel) servicePackage.getModel();


            //delete row
            if(servicePackage.getSelectedRowCount()==1 ){
            //if single row is selected thatn delete
                tblModel.removeRow(servicePackage.getSelectedRow());
                JOptionPane.showMessageDialog(null,"Service Package is Deleted");
            }
            else{
                if(servicePackage.getRowCount() == 0){
                    //if table is empty
                    JOptionPane.showMessageDialog(this,"Table is Empty");
                }
            }



        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Cannot delete");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    /**
     * @param args the command line arguments
     */                            
                // TODO add your handling code here:
                String serviceName = serviceNameField.getText();
                String serviceCount = serviceCountField.getText();
                String serviceFee = serviceFeeField.getText();
                String description = descriptionArea.getText();
                
                /**
                 * @param args the command line arguments
                 */
                
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");
                    
                    
                    if(serviceName.equals("") || serviceCount.equals("") || serviceFee.equals("") || description.equals("")){
                        JOptionPane.showMessageDialog(this,"Please enter Service Package details!");
                    }
                    else{
                        String PATTERN = "^\\s*[\\da-zA-Z][\\da-zA-Z\\s]*$";
                        Pattern patt = Pattern.compile(PATTERN);
                        Matcher match;
                        match = patt.matcher(serviceNameField.getText());
                        if(!match.matches()){
                            JOptionPane.showMessageDialog(this,"Please enter letters!");
                        }
                        else{
                            String PATTERN2 = "^[0-9]{0,9}$";
                            Pattern patt2 = Pattern.compile(PATTERN2);
                            Matcher match2;
                            match2 = patt2.matcher(serviceFeeField.getText());
                            
                            if(!match.matches()){
                                JOptionPane.showMessageDialog(this,"Please enter numbers!");
                            }
                            else{
                                String PATTERN1 = "^[0-9]{0,9}$";
                                Pattern patt1 = Pattern.compile(PATTERN1);
                                Matcher match1;
                                match1 = patt1.matcher(serviceFeeField.getText());
                                
                                
                                
                                if(!match1.matches()){
                                    JOptionPane.showMessageDialog(this,"Please enter numbers!");
                                }
                                
                                else{
                                    insert = con1.prepareStatement("Select 1 from servicepackage where serviceName = ?");
                                    insert.setString(1, serviceNameField.getText());
                                    
                                    ResultSet r = insert.executeQuery();
                                    
                                    int a = 0;
                                    
                                    while(r.next()){
                                        a = r.getInt("1");
                                    }
                                    if(a == 1){
                                        JOptionPane.showMessageDialog(this,"Service package is already added!");
                                    }
                                    else{
                                        insert = con1.prepareStatement("insert into servicepackage(serviceName,packageCount,PackageFee,serviceDescription) values(?,?,?,?)");
                                        
                                        insert.setString(1, serviceNameField.getText());
                                        insert.setString(2, serviceCountField.getText());
                                        insert.setString(3, serviceFeeField.getText());
                                        insert.setString(4, descriptionArea.getText());
                                        insert.executeUpdate();
                                        
                                        //JOptionPane.showMessageDialog(this, "Service Package Added");
                                        table_update();
                                    }
                                }
                            }
                        }
                    }
                }
                catch (ClassNotFoundException | SQLException ex) {
                    //JOptionPane.showMessageDialog(this, "Cant insert ");
                    Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
                }
            
    }//GEN-LAST:event_addButtonActionPerformed


    private void servicePackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
        int selectedIndex = servicePackage.getSelectedRow();

        serviceId.setText(df.getValueAt(selectedIndex, 0).toString());
        serviceNameField.setText(df.getValueAt(selectedIndex, 1).toString());
        serviceCountField.setText(df.getValueAt(selectedIndex, 2).toString());
        serviceFeeField.setText(df.getValueAt(selectedIndex, 3).toString());
        descriptionArea.setText(df.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_labMouseClicked


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int c;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

            insert = con1.prepareStatement("select * from servicepackage");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("packageId"));
                    v2.add(rs.getString("serviceName"));
                    v2.add(rs.getString("packageCount"));
                    v2.add(rs.getString("PackageFee"));
                    v2.add(rs.getString("serviceDescription"));
                }

                df.addRow(v2);
            }
        }

        catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(MobileServiceAddPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MobileServiceLogin logout = new MobileServiceLogin();
        logout.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void demoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoBtnActionPerformed
        // TODO add your handling code here:
        serviceNameField.setText("Rapid Antigen");
        serviceCountField.setText("10");
        serviceFeeField.setText("4000");
        descriptionArea.setText("Provide Rapid Antigen test at home");
    }//GEN-LAST:event_demoBtnActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileServiceAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileServiceAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileServiceAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileServiceAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileServiceAddPackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addServiceCount;
    private javax.swing.JLabel addServiceFee;
    private javax.swing.JLabel addServiceServiceName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton demoBtn;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField serviceCountField;
    private javax.swing.JTextField serviceFeeField;
    private javax.swing.JLabel serviceId;
    private javax.swing.JTextField serviceNameField;
    private javax.swing.JTable servicePackage;
    // End of variables declaration//GEN-END:variables
}
