/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class MobileServiceReserve extends javax.swing.JFrame {

    Connection con1;
    PreparedStatement insert, update, delete;
    PreparedStatement pst = null;
    ResultSet rs = null;
    final String password = "";
    final String userName = "root";
    final String URL = "jdbc:mysql://localhost:3308/channelingcenter";

    /**
     * Creates new form ManiReserveMobileServiceTEST
     */
   
    
    public MobileServiceReserve() {
        initComponents();
//        setimg();
//        jPanel2.setBackground(new Color(255,255,255,120));

        try {
            //set connection
            Class.forName("com.mysql.jdbc.Driver");
            con1 = (Connection) DriverManager.getConnection(URL, userName, password);

        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Stock already exist!");

        }
        updateCombo();
        
    }
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };

    private void updateCombo() {

        try {

            serName.removeAllItems();

            insert = con1.prepareStatement("select serviceName from servicepackage ");

            ResultSet result = insert.executeQuery();

            while (result.next()) {
                serName.addItem(result.getString("serviceName"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    private void decrementCount() {
        //decrementing the count from the relevant service package
        try {

            String sName = serName.getSelectedItem().toString();
            insert = con1.prepareStatement("select packageCount from servicepackage where serviceName = ?");
            insert.setString(1, sName);

            ResultSet r1 = insert.executeQuery();
            r1.next();
            String serCount = r1.getString("packageCount");

            int count2 = Integer.parseInt(serCount);
            count2 = count2 - 1;
            String count3 = Integer.toString(count2);

            update = con1.prepareStatement("update servicepackage set packageCount='" + count3 + "' where serviceName = ?");
            update.setString(1, sName);
            update.executeUpdate();

            BringServiceId();
            
        } catch (SQLException ex) {
            Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);

        }

    }
    
     
    private void BringServiceId() {
        
        try {
            String billno = bno.getText();
            insert = con1.prepareStatement("select serviceId from mobileservice group by serviceId order by serviceId desc limit 1");
            ResultSet rs = insert.executeQuery();
            
            while(rs.next()){
                bno.setText(rs.getString("serviceId"));
            }
        } catch (SQLException ex) {
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        contactNumberLabel = new javax.swing.JLabel();
        pNameLabel = new javax.swing.JLabel();
        testChargeTxtField = new javax.swing.JTextField();
        testNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        testChargeLabel = new javax.swing.JLabel();
        pNameTxtfield = new javax.swing.JTextField();
        contactNumberTxtfield1 = new javax.swing.JTextField();
        testChargeLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        serName = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        bno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 234, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contactNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNumberLabel.setText("Contact Number");

        pNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pNameLabel.setText("Patient's Name");

        testChargeTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        testChargeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testChargeTxtFieldActionPerformed(evt);
            }
        });

        testNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        testNameLabel.setText("Service Name");

        jButton1.setBackground(new java.awt.Color(53, 92, 125));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(53, 92, 125));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        testChargeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        testChargeLabel.setText("Service Charge");

        pNameTxtfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pNameTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTxtfieldActionPerformed(evt);
            }
        });

        contactNumberTxtfield1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNumberTxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTxtfield1ActionPerformed(evt);
            }
        });

        testChargeLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        testChargeLabel1.setText("Address");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Add Mobile Service");

        jButton7.setBackground(new java.awt.Color(53, 92, 125));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        serName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                serNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        serName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serNameActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(53, 92, 125));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        bno.setBackground(new java.awt.Color(214, 234, 245));
        bno.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(contactNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(contactNumberTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testNameLabel)
                                    .addComponent(testChargeLabel))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(testChargeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(serName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(pNameLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(pNameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(testChargeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testChargeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testChargeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testChargeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testChargeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testChargeTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
        String sName = serName.getSelectedItem().toString();
        insert = con1.prepareStatement("select packageCount from servicepackage where serviceName = ?");
        insert.setString(1, sName);

        ResultSet r1 = insert.executeQuery();
        r1.next();
        String serCount = r1.getString("packageCount");

        int count4 = Integer.parseInt(serCount);
        
        if(count4 == 0){
            
            JOptionPane.showMessageDialog(this, "no more services available from the "+sName+" category");
            
        }else{
            
            String cno;
        cno = contactNumberTxtfield1.getText();
        String pname = pNameTxtfield.getText();
        String tcharge = pNameTxtfield.getText();
        String tname = serName.getSelectedItem().toString();
        String maddress = jTextArea1.getText();

       
        try {

            Class.forName("com.mysql.jdbc.Driver");

            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter", "root", "");

            insert = con1.prepareStatement("SELECT patientId from patient where contactNo = ?");
            insert.setString(1, cno);

            ResultSet RESULT = insert.executeQuery();
            RESULT.next();
            String patid = RESULT.getString("patientId");

            insert = con1.prepareStatement("select s.packageId from  servicepackage s where s.serviceName=?");
            insert.setString(1, tname);

            //saving the package id to the mobile service table
            ResultSet RESULT1 = insert.executeQuery();
            RESULT1.next();
            String packid = RESULT1.getString("s.packageId");

            
            String sql = "insert into mobileservice (packageId,serAddress,patientId) values(?,?,?)";
            insert = (PreparedStatement) con1.prepareStatement(sql);

            insert.setString(1, packid);
            insert.setString(2, maddress);
            insert.setString(3, patid);

            insert.executeUpdate();

            decrementCount();
            JOptionPane.showMessageDialog(this, "succesfully added");

        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
    } catch (SQLException ex) {
            Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
        }  
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        pNameTxtfield.setText("");
        if (contactNumberTxtfield1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No patient record");
        } else {

            try {

                Class.forName("com.mysql.jdbc.Driver");

                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter", "root", "");
                PreparedStatement insert = con1.prepareStatement("select fullName from patient where contactNo= ?");
                insert.setString(1, contactNumberTxtfield1.getText());
                ResultSet rs = insert.executeQuery();

                while (rs.next()) {

                    pNameTxtfield.setText(rs.getString("fullName"));
                }

            } catch (SQLException ex) {

                Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pNameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTxtfieldActionPerformed

    private void contactNumberTxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTxtfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTxtfield1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MobileServiceMain la = new MobileServiceMain();
        la.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void serNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serNameActionPerformed

    }//GEN-LAST:event_serNameActionPerformed

    private void serNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_serNamePopupMenuWillBecomeInvisible

        String item = (String) serName.getSelectedItem();
        String sql = "select PackageFee from servicepackage where serviceName=?";

        try {
            pst = con1.prepareStatement(sql);
            pst.setString(1, item);
            rs = pst.executeQuery();

            if (rs.next()) {
                testChargeTxtField.setText(rs.getString("PackageFee"));
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_serNamePopupMenuWillBecomeInvisible

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");
            
            String billno = bno.getText();

            delete = con1.prepareStatement("delete from mobileservice where serviceId = ?");
            delete.setString(1, billno);
            delete.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Reservation Deleted");
            
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Can not delete");
                Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MobileServiceReserve.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        
      
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileServiceReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileServiceReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileServiceReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileServiceReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileServiceReserve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bno;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JTextField contactNumberTxtfield1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JTextField pNameTxtfield;
    private javax.swing.JComboBox<String> serName;
    private javax.swing.JLabel testChargeLabel;
    private javax.swing.JLabel testChargeLabel1;
    private javax.swing.JTextField testChargeTxtField;
    private javax.swing.JLabel testNameLabel;
    // End of variables declaration//GEN-END:variables
}
