package hospitalmanagmentsystem;


import hospitalmanagmentsystem.MobileServiceLogin;
import hospitalmanagmentsystem.MobileServiceMain;

import java.awt.Color;
import java.awt.Image;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class MobileServiceUpdatePackage extends javax.swing.JFrame {

     private Connection con1;
    private PreparedStatement insert;
    private PreparedStatement delete;
    private DefaultTableModel tblModel;
    /**
     * Creates new form ManiUPDATEDtest
     */
    public MobileServiceUpdatePackage() {
        initComponents();
        setRecordsToTable();
//        setimg();
//        jPanel1.setBackground(new Color(255,255,255,120));
    }
    
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };

    public void setRecordsToTable() {
        
         try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter", "root", "");
                Statement st = con1.createStatement();
                String sql = "select * from servicepackage";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    //data will be added until finish
                    String serviceId = String.valueOf(rs.getInt("packageId"));
                    String serviceName = rs.getString("serviceName");
                    String serviceCount = rs.getString("packageCount");
                    String serviceFee = String.valueOf(rs.getInt("PackageFee"));
                    String serviceDes = rs.getString("serviceDescription");

                    String tbData[] = {serviceId, serviceName, serviceCount, serviceFee, serviceDes};
                    DefaultTableModel tblModel = (DefaultTableModel) servicePackage.getModel();

                    //add string array
                    tblModel.addRow(tbData);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void search(String str) {
        tblModel = (DefaultTableModel) servicePackage.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(tblModel);
        servicePackage.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        serviceId = new javax.swing.JLabel();
        addServiceServiceName = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JTextField();
        addServiceCount = new javax.swing.JLabel();
        serviceCountField = new javax.swing.JTextField();
        addServiceFee = new javax.swing.JLabel();
        serviceFeeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicePackage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));

        jButton5.setBackground(new java.awt.Color(53, 92, 125));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Mobile Service");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Service Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Search");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Enter Service Name");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        serviceId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        addServiceServiceName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceServiceName.setText("Mobile Service Name  ");

        serviceNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serviceNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceNameFieldActionPerformed(evt);
            }
        });

        addServiceCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceCount.setText("Count  ");

        serviceCountField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serviceCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCountFieldActionPerformed(evt);
            }
        });

        addServiceFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addServiceFee.setText("Service Fee  ");

        serviceFeeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Description");

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane4.setViewportView(descriptionArea);

        editButton.setBackground(new java.awt.Color(53, 92, 125));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(53, 92, 125));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        servicePackage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        servicePackage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Mobile Service Name", "Count", "Service Fee", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        servicePackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicePackageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(servicePackage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addServiceServiceName)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addServiceCount)
                                    .addComponent(serviceCountField, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(addServiceFee)
                                    .addComponent(serviceFeeField)
                                    .addComponent(serviceNameField))
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(28, 28, 28)
                .addComponent(addServiceServiceName)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(addServiceCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(addServiceFee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MobileServiceMain back = new MobileServiceMain();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MobileServiceLogin bak = new MobileServiceLogin();
        bak.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void servicePackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicePackageMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = servicePackage.getSelectedRow();

        serviceId.setText(servicePackage.getValueAt(selectedRowIndex, 0).toString());
        serviceNameField.setText(servicePackage.getValueAt(selectedRowIndex, 1).toString());
        serviceCountField.setText(servicePackage.getValueAt(selectedRowIndex, 2).toString());
        serviceFeeField.setText(servicePackage.getValueAt(selectedRowIndex, 3).toString());
        descriptionArea.setText(servicePackage.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_servicePackageMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        String Did = null;
        try {

            delete = con1.prepareStatement("DELETE FROM servicepackage where packageId = ?") ;

            delete.setString(1, serviceId.getText());
            delete.executeUpdate();

            DefaultTableModel tblModel = (DefaultTableModel) servicePackage.getModel();

            //delete row
            if(servicePackage.getSelectedRowCount()==1 ){
                //if single row is selected thaen delete
                //tblModel.removeRow(servicePackage.getSelectedRow());
                JOptionPane.showMessageDialog(null,"Service Package is Deleted");
            }
            else{
                JOptionPane.showMessageDialog(this,"delete unsuccesfull");
            }

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Cannot delete");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
        int selectedIndex = servicePackage.getSelectedRow();

        //getting new data
        String serviceName = serviceNameField.getText();
        String serviceCount = serviceCountField.getText();
        String serviceFee = serviceFeeField.getText();
        String description = descriptionArea.getText();

        if(serviceName.equals("") || serviceCount.equals("") || serviceFee.equals("") ||descriptionArea.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter Service Package details!");
        }
        else{
            String PATTERN = "^\\s*[\\da-zA-Z][\\da-zA-Z\\s]*$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match;
            match = patt.matcher(serviceNameField.getText());
            if(!match.matches()){
                JOptionPane.showMessageDialog(this,"Please use only letters!");
            }
            else{
                String PATTERN2 = "^[0-9]{0,9}$";
                Pattern patt2 = Pattern.compile(PATTERN);
                Matcher match2;
                match2 = patt2.matcher(serviceCountField.getText());
                if(!match.matches()){
                    JOptionPane.showMessageDialog(this,"Please enter a valid name");
                }
                else{
                    String PATTERN1 = "^[0-9]{0,9}$";
                    Pattern patt1 = Pattern.compile(PATTERN1);
                    Matcher match1;
                    match1 = patt1.matcher(serviceFeeField.getText());

                    if(!match1.matches()){
                        JOptionPane.showMessageDialog(this,"Please enter numbers!");
                    }

                    else{
                        try {
                            Class.forName("com.mysql.jdbc.Driver");

                            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");

                            insert = con1.prepareStatement("update servicepackage set serviceName = ?, packageCount = ? , PackageFee = ?, serviceDescription = ? where packageId = ?");

                            insert.setString(1, serviceNameField.getText());
                            insert.setString(2, serviceCountField.getText());
                            insert.setString(3, serviceFeeField.getText());
                            insert.setString(4, descriptionArea.getText());
                            insert.setString(5, serviceId.getText());
                            insert.executeUpdate();

                            insert.executeUpdate();

                            JOptionPane.showMessageDialog(this, "Record Updated");
                            //table_update();

                            serviceId.setText("");
                            serviceNameField.setText("");
                            serviceCountField.setText("");
                            serviceFeeField.setText("");
                            descriptionArea.setText("");
                        }
                        catch (SQLException ex) {

                            Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        catch (ClassNotFoundException ex){
                            Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        table_update();
                    }
                }
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void serviceCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceCountFieldActionPerformed

    private void serviceNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceNameFieldActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String searchString = jTextField1.getText();
        search(searchString);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Enter Service Name"))
        {
            jTextField1.setText("");
            jTextField1.setForeground(new Color(153,153,153));
        }      
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
    if(jTextField1.getText().equals(""))
    {
        jTextField1.setText("Enter Service Name");
        jTextField1.setForeground(new Color(153,153,153));
    }
        
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileServiceUpdatePackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addServiceCount;
    private javax.swing.JLabel addServiceFee;
    private javax.swing.JLabel addServiceServiceName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField serviceCountField;
    private javax.swing.JTextField serviceFeeField;
    private javax.swing.JLabel serviceId;
    private javax.swing.JTextField serviceNameField;
    private javax.swing.JTable servicePackage;
    // End of variables declaration//GEN-END:variables

   
    private void table_update() {

         int c;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter","root","");
            
            

            insert = con1.prepareStatement("select * from servicepackage where packageID = ?");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c = res.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) servicePackage.getModel();
            df.setRowCount(0);

            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("packageId"));
                    v2.add(rs.getString("serviceName"));
                    v2.add(rs.getString("packageCount"));
                    v2.add(rs.getString("PackageFee"));
                    v2.add(rs.getString("serviceDescription"));
                }

                df.addRow(v2);
            }
        }

        catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(MobileServiceUpdatePackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
