/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashmi
 */
public class paymentFinalBill extends javax.swing.JFrame {

    Connection con = null;//create connection
    PreparedStatement update, insert, delete = null;//create preparedStatement
    final String password = "";//databse password
    final String userName = "root";//database username
    final String URL = "jdbc:mysql://localhost:3308/channelingcenter";//database url
    int labAmount, mobileAmount, other, totAmount;
    String payMethod;

    /**
     * Creates new form fullFinalBill
     */
    //fullFinalBill class constructor
    public paymentFinalBill() {
        initComponents();
//        setimg();
//        jPanel1.setBackground(new Color(255,255,255,120));
        try {
            //set connection
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, userName, password);//create database connection

        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Final bill already registered!");

        }
    }
    
//    public void setimg(){
//        ImageIcon imageicon = new ImageIcon("C:\\Users\\singer\\Downloads\\user_roles\\user_roles\\icon14.png");
//        Image img = imageicon.getImage();
//        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        backg.setIcon(scaledIcon);
//        
//    };

    //create showDate() to get the current date
    public void showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(sd.format(d));

    }

    //create showTime() to get the current time
    public void showTime() {
        Calendar cal = new GregorianCalendar();
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        time.setText(hour + ":" + minute);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientContact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        billNo = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totLab = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totMS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        creditCard = new javax.swing.JRadioButton();
        cash = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        otherFee = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Final Bill");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Patient Contact Number");

        patientContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patientContactKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contact Number");

        name.setEditable(false);
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        age.setEditable(false);
        age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        contactNo.setEditable(false);
        contactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bill No");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Time");

        billNo.setEditable(false);
        billNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        date.setEditable(false);
        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Total Lab Charge");

        totLab.setEditable(false);
        totLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Total Mobile Service Charge");

        totMS.setEditable(false);
        totMS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Total Amount");

        totalAmount.setEditable(false);
        totalAmount.setBackground(new java.awt.Color(204, 255, 255));
        totalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        area.setColumns(20);
        area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton2.setBackground(new java.awt.Color(53, 92, 125));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(53, 92, 125));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(53, 92, 125));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Pay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(53, 92, 125));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select payment method");

        creditCard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creditCard.setText("Creditcard");
        creditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardActionPerformed(evt);
            }
        });

        cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Others");

        otherFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));

        clearButton.setBackground(new java.awt.Color(53, 92, 125));
        clearButton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setActionCommand("");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(104, 104, 104)
                                    .addComponent(totLab, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(totMS)
                                        .addComponent(otherFee))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(age)
                                            .addComponent(contactNo)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(patientContact, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(date)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(patientContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totLab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totMS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(otherFee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(creditCard)
                            .addComponent(cash))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Back button 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new cashierMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Pay button to direct to the relevant payment method page
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(creditCard.isSelected() == false && cash.isSelected() == false ){
            JOptionPane.showMessageDialog(this, "Payment method is empty");
        }
        else if (creditCard.isSelected()) {
            String totamount = totalAmount.getText();
            String patientID = patientContact.getText();
            String billNO = billNo.getText();
            String date1 = date.getText();
            String time1 = time.getText();

            //send relavant data to the credit card payment interface
            new paymentCreditcard(totamount, patientID, billNO, date1, time1).setVisible(true);
            this.dispose();
            }
            else if (cash.isSelected()) {
                    String totamount = totalAmount.getText();
                    String patientID = patientContact.getText();
                    String billNO = billNo.getText();
                    String date2 = date.getText();
                    String time2 = time.getText();

                    //send relavant data to the cash payment interface
                    new paymentCash(totamount, patientID, billNO, date2, time2).setVisible(true);
                    this.dispose();
                }

    }//GEN-LAST:event_jButton4ActionPerformed

    //search button - retrieve patient details by searching patient's contact number
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //select patient details from patient table by searching contact number
            String sql1 = "select fullName , age , contactNo from patient where contactNo=?";

            PreparedStatement retrieve1 = con.prepareStatement(sql1);
            retrieve1.setInt(1, Integer.parseInt(patientContact.getText()));
            ResultSet result1 = retrieve1.executeQuery();

            if (result1.next()) {
                name.setText(result1.getString("fullName"));
                age.setText(result1.getString("age"));
                contactNo.setText(result1.getString("contactNo"));
            }else{
               
                JOptionPane.showMessageDialog(this, "No patient with this contact number");
            }

            //select total lab charge from labbok table according to the patient contact number
            String sql2 = "select sum(t.charge)as tot from labtest t, labbook b, patient p "
                    + "where t.testId = b.testId and b.labStatus = 0 and b.patientId=p.patientId and p.contactNo=?";

            PreparedStatement retrieve2 = con.prepareStatement(sql2);
            retrieve2.setInt(1, Integer.parseInt(patientContact.getText()));
            ResultSet result2 = retrieve2.executeQuery();

            if(result2.next()){
                 totLab.setText(result2.getString("tot"));
            }else{
               
                JOptionPane.showMessageDialog(this, "There is no any unpaid lab booking");
                //totLab.setText("0");
            }
           

            //select total mobile service fee from mobileservice and servicepackage table according to the patient contact number
            String sql3 = "select sum(p.PackageFee) as tot1 from servicepackage p, mobileservice m, patient pa "
                    + "where p.packageId = m.packageId and m.serviceStatus = 0 and m.patientId=pa.patientId and pa.contactNo=?";

            PreparedStatement retrieve3 = con.prepareStatement(sql3);
            retrieve3.setInt(1, Integer.parseInt(patientContact.getText()));
            ResultSet result3 = retrieve3.executeQuery();

            if(result3.next()){
                totMS.setText(result3.getString("tot1"));
                
            }else{
                
                JOptionPane.showMessageDialog(this, "There is no any unpaid mobile service booking");
                //totMS.setText("0");
            }
            

            //select bill number from payment table and print it        
            String sql4 = "select finalBillId +1 as Bill_Num from payment group by finalBillId order by finalBillId desc limit 1";

            PreparedStatement retrieve4 = con.prepareStatement(sql4);
            ResultSet result4 = retrieve4.executeQuery();

            result4.next();

            billNo.setText(result4.getString("Bill_Num"));

            showDate();//print current date
            showTime();//print current time

            otherFee.setText("1000");

            try {
                labAmount = Integer.parseInt(totLab.getText());
            } catch (NumberFormatException ex1) {
                labAmount = 0;
            }

            try {
                mobileAmount = Integer.parseInt(totMS.getText());
            } catch (NumberFormatException ex1) {
                mobileAmount = 0;
            }
            other = Integer.parseInt(otherFee.getText());
            totAmount = labAmount + mobileAmount + other;

            totalAmount.setText(String.valueOf(totAmount));

            String num = "";
            num += totAmount;
            totalAmount.setText(num);

        } catch (Exception ex) {
            System.out.println(ex);
            //JOptionPane.showMessageDialog(this, "No patient with this contact number");

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //create totAmount() method to calculate total amount by adding total labcharge and total service fee

    //print button to print the bill
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            area.print();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //Ok button 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        area.setText(area.getText() + "\t" + "  " + "UNION CHANNELING CENTER\n");
        area.setText(area.getText() + "\t" + "       " + "Doctor Channeling Bill\n\n");

        area.setText(area.getText() + "Bill No.\t\t: " + billNo.getText() + "\n");
        area.setText(area.getText() + "Date\t\t: " + date.getText() + "\n");
        area.setText(area.getText() + "Time\t\t: " + time.getText() + "\n\n");

        area.setText(area.getText() + "Patient and Channelling Details\n\n");
        area.setText(area.getText() + "Name\t\t: " + name.getText() + "\n");
        area.setText(area.getText() + "Age\t\t: " + age.getText() + "\n");
        area.setText(area.getText() + "Contact No\t\t: " + contactNo.getText() + "\n\n");

        area.setText(area.getText() + "Lab testID\t\tLab test name\t\tCharge\n");

        try {
            String sql5 = "select t.testId as testid, t.testName as testname, t.charge as testcharge from labtest t, labbook b, patient p where t.testId = b.testId and b.labStatus = 0 and b.patientId=p.patientId and p.contactNo=? ";
            PreparedStatement retrieve5 = con.prepareStatement(sql5);
            retrieve5.setInt(1, Integer.parseInt(patientContact.getText()));
            
            try{
            ResultSet result5 = retrieve5.executeQuery();
    
            if (result5.next()) {
                int testid = Integer.parseInt(result5.getString("testid"));
                String testname = result5.getString("testname");
                int testfee = Integer.parseInt(result5.getString("testcharge"));
                area.setText(area.getText() + Integer.parseInt(result5.getString("testid")) + "\t" + "\t" + result5.getString("testname") + "\t" + "\t"+ Integer.parseInt(result5.getString("testcharge")) + "\n");
            }else{
                labAmount = 0;//if lab amount is null, then lab amount initialize to 0
            }
            }catch(NumberFormatException ex){
                 System.out.println("error1");
                
            }
            
            area.setText(area.getText() + "\n");
            area.setText(area.getText() + "Total lab cahrge: Rs." + Integer.parseInt(totLab.getText()));
            area.setText(area.getText() + "\n\n");
            
            area.setText(area.getText() + "Mobile Service Id\tPackage Id\tService name\tCharge\n");
            
            String sql6 = "select m.serviceId as serviceid,  m.packageId as packageid, p.serviceName as name, p.PackageFee as fee from servicepackage p, mobileservice m, patient pa where p.packageId = m.packageId and m.serviceStatus = 0 and m.patientId=pa.patientId and pa.contactNo=?";
            PreparedStatement retrieve6 = con.prepareStatement(sql6);
            retrieve6.setInt(1, Integer.parseInt(patientContact.getText()));
             
            try{
                
                  ResultSet result6 = retrieve6.executeQuery();
                  
                  if(result6.next()) {
                    int sid = Integer.parseInt(result6.getString("serviceid"));
                    int pid = Integer.parseInt(result6.getString("packageid"));
                    String sname = result6.getString("name");
                    int sfee = Integer.parseInt(result6.getString("fee"));

                    area.setText(area.getText() + Integer.parseInt(result6.getString("serviceid")) + "\t" + Integer.parseInt(result6.getString("packageid")) + "\t" + result6.getString("name") + "\t" + Integer.parseInt(result6.getString("fee")) + "\n");
                   }else{
                    totMS.setText("0");
                    mobileAmount = 0;//if service charge is null, then service charge initialize to 0

                     }
                
                
                }catch(NumberFormatException ex){
                     System.out.println("error2");
                }
          
            area.setText(area.getText() + "\n");
            area.setText(area.getText() + "Total service cahrge: Rs." + Integer.parseInt(totMS.getText()));
            area.setText(area.getText() + "\n\n");

            area.setText(area.getText() + "\n");
            area.setText(area.getText() + "Other cahrges: Rs." + Integer.parseInt(otherFee.getText()));
            area.setText(area.getText() + "\n\n");

            
            //calculate total amount by adding total lab amount,mobileamount and other charges
            otherFee.setText("1000");//set 10000 as other charge

            try {
                labAmount = Integer.parseInt(totLab.getText());//get total lab amount and assign it into a variable
            } catch (NumberFormatException ex1) {//if labamount gets null, then catch numberformat exception
                labAmount = 0;
            }

            try {
                mobileAmount = Integer.parseInt(totMS.getText());//get total service charge and assign it into a variable
            } catch (NumberFormatException ex1) {//if service charge gets null, then catch numberformat exception
                mobileAmount = 0;
            }
            other = Integer.parseInt(otherFee.getText());//get other charges and assign it into a variable
            totAmount = labAmount + mobileAmount + other;//calculate total amount

            totalAmount.setText(String.valueOf(totAmount));

            area.setText(area.getText() + "\n");
            area.setText(area.getText() + "Total Amount: Rs." + totalAmount.getText());
            area.setText(area.getText() + "\n");

        } catch (Exception ex) {
            System.out.println(ex);

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void creditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardActionPerformed
        // TODO add your handling code here:
        payMethod = "Creditcard";
//validate radio buttons
      if (creditCard.isSelected()) {
      cash.setSelected(false);
      }
    }//GEN-LAST:event_creditCardActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
         payMethod = "Cash";
//validate radio buttons
      if (cash.isSelected()) {
      creditCard.setSelected(false);
      }
    }//GEN-LAST:event_cashActionPerformed

    private void patientContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientContactKeyReleased
        // TODO add your handling code here:
        
        String PATTERN = "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match;
        match = patt.matcher(patientContact.getText());
        if(!match.matches()){
            jLabel14.setText("Please enter correct format!");
        }
        else{
            jLabel14.setText(null);
        }
    }//GEN-LAST:event_patientContactKeyReleased

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        billNo.setText(null);
        //miligram.setText(null);
        date.setText(null);
        time.setText(null);
        name.setText(null);
        age.setText(null);
        contactNo.setText(null);
        totLab.setText(null);
        totMS.setText(null);
        totalAmount.setText(null);
        otherFee.setText(null);
        cash.setText(null);
        creditCard.setText(null);

        //Docname.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentFinalBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField billNo;
    private javax.swing.JRadioButton cash;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField contactNo;
    private javax.swing.JRadioButton creditCard;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField otherFee;
    private javax.swing.JTextField patientContact;
    private javax.swing.JTextField time;
    private javax.swing.JTextField totLab;
    private javax.swing.JTextField totMS;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables
}
