/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import com.toedter.calendar.JMonthChooser;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author singer
 */
public class PharmacyReport extends javax.swing.JFrame {

    Boolean result;
    Connection con1;
    PreparedStatement insert;

    /**
     * Creates new form PharmacyReport
     */
    public PharmacyReport() {
        initComponents();
    }
    
    public void showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        reportDate.setText(sd.format(d));
    }

    public void getMax2() {
        int max2 = 0;
        for (int i = 0; i < reportTable.getRowCount(); i++) {
            int val = Integer.parseInt(reportTable.getValueAt(i, 1).toString());
            if (val > max2) {
                max2 = val;
            }
        }
        maxTxt.setText(Integer.toString(max2));
    }

    public void getMin() {
        int min = 0;
        
        for (int i = 0; i < reportTable.getRowCount(); i++) {
            if (i == 0) {
                min = Integer.parseInt(reportTable.getValueAt(i, 1).toString());
            } else {
                int val = Integer.parseInt(reportTable.getValueAt(i, 1).toString());
                if (val < min) {
                    min = val;
                }
            }
        }
        minTxt.setText(Integer.toString(min));
    }
    
    public void getSum() {
        int sum = 0;
        for (int i = 0; i < reportTable.getRowCount(); i++) {
            sum = sum + Integer.parseInt(reportTable.getValueAt(i, 2).toString());
        }
        totInco.setText(Integer.toString(sum));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        reportTitle = new javax.swing.JLabel();
        specializationL = new javax.swing.JLabel();
        drugCategory = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        monthlabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        generateR = new javax.swing.JButton();
        backg = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        totInco = new javax.swing.JTextField();
        totAppL = new javax.swing.JLabel();
        totAppL2 = new javax.swing.JLabel();
        totItem = new javax.swing.JTextField();
        minTxt = new javax.swing.JTextField();
        maxTxt = new javax.swing.JTextField();
        maxDrugLabel = new javax.swing.JLabel();
        minDrugLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reportDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 234, 245));

        backBtn.setBackground(new java.awt.Color(53, 92, 125));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        reportTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reportTitle.setText("Drug usage Report");

        specializationL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        specializationL.setText("Select Specialization:");

        drugCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drugCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablets", "Liquids", "Capsules", "Injections", "Tropical Medicine" }));
        drugCategory.setBorder(null);
        drugCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCategoryActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(153, 204, 255));
        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchBtn.setText("search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        reportTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "no of items sold", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(reportTable);

        jMonthChooser1.setMinimumSize(new java.awt.Dimension(130, 24));

        monthlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthlabel.setText("Select Month:");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        generateR.setBackground(new java.awt.Color(53, 92, 125));
        generateR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        generateR.setForeground(new java.awt.Color(255, 255, 255));
        generateR.setText("Print");
        generateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(53, 92, 125));
        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(53, 92, 125));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        totInco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totInco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totIncoActionPerformed(evt);
            }
        });

        totAppL.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        totAppL.setText("Total units sold  :");

        totAppL2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        totAppL2.setText("Total Income (Rs) :");

        totItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totItemActionPerformed(evt);
            }
        });

        minTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTxtActionPerformed(evt);
            }
        });

        maxDrugLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        minDrugLabel.setBackground(new java.awt.Color(204, 204, 204));
        minDrugLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lowest unit sales  :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Highest unit sales  :");

        reportDate.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        reportDate.setForeground(new java.awt.Color(255, 255, 255));
        reportDate.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(generateR, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specializationL)
                                    .addComponent(monthlabel))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(drugCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(backg)
                        .addGap(44, 44, 44)
                        .addComponent(reportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(reportDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(maxTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(minTxt))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minDrugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxDrugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(628, 628, 628)
                .addComponent(totAppL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totItem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totAppL2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totInco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totAppL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totAppL2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totInco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backg)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(monthlabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(specializationL)
                                        .addComponent(drugCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(minDrugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(maxDrugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(reportDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        /* adminDoctorMain back1 = new adminDoctorMain();
        back1.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        //getMax2();
        int date1 = jMonthChooser1.getMonth() + 1;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3308/channelingcenter", "root", "");
            insert = con1.prepareStatement("select sum(stock.unitPrice * billdrug.itemQty) as totIncome, sum(billdrug.itemQty) as tot , billdrug.drugId, drug.drugName "
                    + "from billdrug, drug, stock, pharmacybill where drug.drugID = stock.drugID AND billdrug.drugId = drug.drugID "
                    + "AND billdrug.PharmacyBillID = pharmacybill.PharmacyBillId AND drug.category = ? AND month(billDate) = ? group by billdrug.drugId , drug.drugName order by tot");
            insert.setString(1, drugCategory.getSelectedItem().toString());
            insert.setInt(2, date1);

            ResultSet rs = insert.executeQuery();

            ResultSetMetaData res = rs.getMetaData();

            int c = res.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) reportTable.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("drug.drugName"));
                    v2.add(rs.getString("tot"));
                    v2.add(rs.getString("totIncome"));
                }
                df.addRow(v2);
            }

            String spl = drugCategory.getSelectedItem().toString();
            //String sql2 = "select count(app.appoId) as 'c' from doctor doc, docappointment app where doc.docId = app.docId and doc.specialization = '"+spl+"' and month(app.appDate) = '"+appdate+"'";
            String sql2 = "select sum(billdrug.itemQty) as 'itemCount' from billdrug , drug , pharmacybill where billdrug.drugId = drug.drugID and pharmacybill.PharmacyBillId = billdrug.PharmacyBillID and drug.category = '" + spl + "'  and month(pharmacybill.billDate) = '" + date1 + "'";
            insert = (com.mysql.jdbc.PreparedStatement) con1.prepareStatement(sql2);
            ResultSet r1 = insert.executeQuery(sql2);
            r1.next();
            String totCount = r1.getString("itemCount");

            totItem.setText(totCount);

            String minDrug = minTxt.getText();
            String maxDrug = maxTxt.getText();
            
            String sql3 = "select sum(billdrug.itemQty) as 'itemCount', drug.drugName from billdrug , drug , pharmacybill where billdrug.drugId = drug.drugID and pharmacybill.PharmacyBillId = billdrug.PharmacyBillID and drug.category = '" + spl + "'  "
                    + "and month(pharmacybill.billDate) = '" + date1 + "' group by drug.drugName having itemCount = '"+minDrug+"'";
            insert = (com.mysql.jdbc.PreparedStatement) con1.prepareStatement(sql3);
            ResultSet r2 = insert.executeQuery(sql3);
            r2.next();
            String min = r2.getString("drug.drugName");
            minDrugLabel.setText(min);
            
             String sql4 = "select sum(billdrug.itemQty) as 'itemCount', drug.drugName from billdrug , drug , pharmacybill where billdrug.drugId = drug.drugID and pharmacybill.PharmacyBillId = billdrug.PharmacyBillID and drug.category = '" + spl + "'  "
                     + "and month(pharmacybill.billDate) = '" + date1 + "' group by drug.drugName having itemCount = '"+maxDrug+"'";
            insert = (com.mysql.jdbc.PreparedStatement) con1.prepareStatement(sql4);
            ResultSet r3 = insert.executeQuery(sql4);
            r3.next();
            String max = r3.getString("drug.drugName");
            maxDrugLabel.setText(max);
   

        } catch (SQLException ex) {
            Logger.getLogger(PharmacyReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PharmacyReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void totIncoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totIncoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totIncoActionPerformed

    private void generateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRActionPerformed
        // TODO add your handling code here:

//        int check = reportTable.getRowCount();
//
//        if (check == 0)
//            JOptionPane.showMessageDialog(this, "No results available!");
//
//        else {
//            int dialogresult = JOptionPane.showConfirmDialog(null, "This will print Pharmacy Drug sales report for the month. Click ok to continue", "Info", JOptionPane.YES_NO_OPTION);
//
//            if (dialogresult == JOptionPane.YES_OPTION) {
//                MessageFormat header = new MessageFormat("Pharmacy drug usage for UCC");
//                MessageFormat footer = new MessageFormat("page 1");
//                try {
//
//                    reportTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//                } catch (PrinterException ex) {
//
//                    //Logger.getLogger(HLabApp.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//
//        }
        
        try{
            area.print();
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_generateRActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int appdate = jMonthChooser1.getMonth() + 1;
        String mymonth;
        SimpleDateFormat sdf1 = new SimpleDateFormat("MM");

        mymonth = sdf1.format(appdate);
        System.out.println(mymonth);
        showDate();

        //System.out.println("Error2");
        area.setText(area.getText() + "\t" + " " + "UNION CHANNELING CENTER\n");
        area.setText(area.getText() + "\t"+ "                " +reportDate.getText() + "\n");
        area.setText(area.getText() + "----------------------Doctor Appointment Summary Report---------------------\n\n");
        area.setText(area.getText() + "Drug Category\t\t\t: " + drugCategory.getSelectedItem().toString() + "\n");
        //System.out.println("Error1");
        area.setText(area.getText() + "Month\t\t\t: " + mymonth + "\n");
        //System.out.println("Error3");
        area.setText(area.getText() + "Total Units Sold\t\t\t: " + totItem.getText() + "\n");
        area.setText(area.getText() + "Total Sales Income (Rs.)\t\t: " + totInco.getText() + "\n");
        area.setText(area.getText() + "----------------------------------------------------------------------------------------------\n\n");
        area.setText(area.getText() + "Drug Name" + "\t\t\t" + "No of items sold" + "\n");
        area.setText(area.getText() + "----------------------------------Unit Sales-----------------------------------------\n\n");
        for (int count = 0; count < reportTable.getRowCount(); count++) {
            area.setText(area.getText() + reportTable.getValueAt(count, 0).toString() + "\t\t\t");
            area.setText(area.getText() + reportTable.getValueAt(count, 1).toString() + "\n");
        }
        area.setText(area.getText() + "------------------------------------Lowest Unit sales-----------------------------------\n\n");
        area.setText(area.getText() + "Drug Name" + "\t\t\t" + "Qty Sold" + "\n\n");
        //area.setText(area.getText() + "Total Appointments\t\t: " + minDrugLabel.getText() + "\n");
        area.setText(area.getText() + minDrugLabel.getText()+ "\t\t\t: " + minTxt.getText() + "\n\n");
        area.setText(area.getText() + "------------------------------------Highest Unit sales-----------------------------------\n\n");
        area.setText(area.getText() + "Drug Name" + "\t\t\t" + "Qty Sold" + "\n\n");
        area.setText(area.getText() + maxDrugLabel.getText() + "\t\t\t: " + maxTxt.getText() + "\n\n");
        //area.setText(area.getText() + "Total Appointments\t\t: " + maxDrugLabel.getText() + "\n");
    }//GEN-LAST:event_viewBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //CReport nd = new CReport();
        // nd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void drugCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugCategoryActionPerformed

    private void totItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totItemActionPerformed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked

        getMax2();
        getMin();
        getSum();

    }//GEN-LAST:event_searchBtnMouseClicked

    private void minTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backg;
    private javax.swing.JComboBox<String> drugCategory;
    private javax.swing.JButton generateR;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maxDrugLabel;
    private javax.swing.JTextField maxTxt;
    private javax.swing.JLabel minDrugLabel;
    private javax.swing.JTextField minTxt;
    private javax.swing.JLabel monthlabel;
    private javax.swing.JLabel reportDate;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel reportTitle;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel specializationL;
    private javax.swing.JLabel totAppL;
    private javax.swing.JLabel totAppL2;
    private javax.swing.JTextField totInco;
    private javax.swing.JTextField totItem;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
